---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-debug-deployment
  labels:
    app: live-debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: live-debug
  template:
    metadata:
      labels:
        app: live-debug
    spec:
      containers:
        - name: live-debug
          image: live-debug-image
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 400m
              memory: 400Mi
---
apiVersion: v1
kind: Service
metadata:
  name: live-debug-service
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: live-debug
  type: LoadBalancer
